# -*- coding: utf-8 -*-
"""Despliegue Practica3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syGTYLa9t6RkpoKBg9mPcT5-NbP_orB2

# Despliegue
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd

#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, variables = pickle.load(open(filename, 'rb'))

#modelo

#Cargamos los datos futuros
#data = pd.read_excel("nuevos_datos.xlsx")
#data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
import pandas as pd

st.title('Predicción del puntaje global en Saber 11')

cole_area_ubicacion = st.selectbox('Área de ubicación del colegio', ['URBANO', 'RURAL'])
cole_caracter = st.selectbox('Carácter del colegio', ['ACADÉMICO', 'NO APLICA', 'TÉCNICO', 'TÉCNICO/ACADÉMICO'])
cole_jornada = st.selectbox('Jornada del colegio', ['COMPLETA', 'MAÑANA', 'NOCHE', 'SABATINA', 'TARDE', 'UNICA'])
cole_naturaleza = st.selectbox('Naturaleza del colegio', ['OFICIAL', 'NO OFICIAL'])
estu_genero = st.selectbox('Género del estudiante', ['M', 'F'])
fami_estratovivienda = st.selectbox('Estrato de la vivienda', ['Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6', 'Sin Estrato'])


#Dataframe
datos = [[cole_area_ubicacion, cole_caracter, cole_jornada, cole_naturaleza, estu_genero, fami_estratovivienda]]
data = pd.DataFrame(datos, columns=['cole_area_ubicacion', 'cole_caracter', 'cole_jornada', 'cole_naturaleza', 'estu_genero', 'fami_estratovivienda']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['cole_area_ubicacion', 'cole_caracter','cole_jornada', 'cole_naturaleza', 'estu_genero', 'fami_estratovivienda'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un margen de error del 12% (MAE)")